
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Xiang Li
description: Xiang Li's homepage

show_downloads: false
google_analytics: G-55SCBLWWL4
